steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/iykra-437909/iykra-sentiment-frontend-app', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/iykra-437909/iykra-sentiment-frontend-app']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'iykra-sentiment-frontend-app'
      - '--image'
      - 'gcr.io/iykra-437909/iykra-sentiment-frontend-app'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/iykra-437909/iykra-sentiment-frontend-app'

options:
  logging: CLOUD_LOGGING_ONLY